#ifndef CARPARK_RULES
#define CARPARK_RULES

#define KEY ("PARKING")

#define ENTRANCES (5)
#define EXITS (5)
#define LEVELS (5)

#define LEVEL_CAPACITY (20)

#define MIN_CAR_SPAWN (1)
#define MAX_CAR_SPAWN (100)
#define LPR_QUEUE_WAIT (2)
#define BOOMGATE_RAISING_TIME (10)
#define BOOMGATE_LOWERING_TIME (10)
#define BOOMGATE_OPENED_TIME (20)
#define CAR_DRIVING_TIME (10)
#define CAR_PARKING_TIME (10)
#define MIN_CAR_PARKED (100)
#define MAX_CAR_PARKED (10000)
#define CAR_LEAVING_TIME (10)

#define MIN_TEMP_CHANGE_TIME (1)
#define MAX_TEMP_CHANGE_TIME (5)

#define TEMP_CHECK_TIME (2)
#define VACUATE_TIMER (20)

#endif
